apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    app: demo
spec:
  containers:
  - name: demo
    image: pingworks/ws-demo:1.4
    ports:
    - containerPort: 8080
    resources:
      limits:
        memory: 1Gi
      requests:
        memory: 1Gi
